server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: movie
    password: movie
  jpa:
    #    hibernate:
    #      ddl-auto: create # ddl ???? (?? ???? create, create-drop ??, ?? ??? update, ?? ??? none, validate)
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create # ddl ???? (?? ???? create, create-drop ??, ?? ??? update, ?? ??? none, validate)
        jdbc:
          batch_size: 80
          batch_versioned_data: true
          generate_statistics: true
        order_inserts: true
        order_updates: true
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect # sql ???? ??? ? ?? ??
logging:
  level:
    root: info
    com.sh.app: debug
api:
  kobis:
    key: '51255ceba3272d0a60a62207435ec085'
  kmdb:
    key: 'P0ZWHCNG459XPX2XEVK5'
  youtube:
    key: 'AIzaSyDBTbARQTqTen5HkWAGSe99h5YnClKc08M'